PREFIX univ: <http://www.mydomain.org/univ/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/22-rdf-schema#>
SELECT ?name ?members_of
WHERE {
	?x univ:has_name ?name;
	univ:member_of ?members_of.
	?members_of univ:dep_city ?city
	FILTER(?city="Patras")
	#filter exists { ?x rdfs:subClassOf univ:Person}
	
}
